app:
  name: "gin_demo"
  mode: "dev"
  port: 18080
  https: false
log:
  level: "info"
  filename: "app.log"
  max_size: 100
  max_age: 30
  max_backups: 7
mysql:
  ip: "127.0.0.1"
  port: 3306
  pwd: "Srun@4000"
  user: "root"
  dbname: "demo"
  max_life_time: 5
  max_open: 100
  max_idle: 50
redis:
  ip: "127.0.0.1"
  port: 6379
  pwd: "Srun@4000"
  index: 0
  pool_size: 100
